name: 🚀 Deploy to InfinityFree

on:
  push:
    branches:
      - main   # O la rama que uses como principal

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout repo
        uses: actions/checkout@v3

      - name: 📂 Upload to InfinityFree
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          server-dir: htdocs/   # 👈 MUY IMPORTANTE: siempre dentro de htdocs
